### ISSUE TITLE
Original repo

### ISSUE THREAD

**Issue by aytek03** [NU-LL/lighttrack-#1]
what is the difference between this repo and original light_track repo?

**Comment by NU-LL** [comment]
The code is basically the same as [lighttrack](https://github.com/Guanghan/lighttrack), this code is only for use in my environment

**Comment by aytek03** [comment]
Hi @NU-LL 

I could not implemented the original repo lighttrack  (I am windows user) since **make** command have not worked properly. Therefore I have found your repo and I have realized that you had changed the some of codes of **lighttrack/lib/setup.py**. Still I cannot implemented 'make file', but I have also changed some of the codes (disable nms.gpu_nms, yaml.safe_load(f) instead of yaml.load(f) ) then it has worked (python demo_video_mobile.py)). Many thanks for the improvement.
